using System;
using System.Collections.Generic;
using System.Text;

namespace Willowcat.EbookDesktopUI.ViewModels
{
    public class EpubListItemViewModel
    {
        #region Member Variables...

        #endregion Member Variables...

        #region Properties...

        #endregion Properties...

        #region Constructors...

        #endregion Constructors...

        #region Methods...

        #endregion Methods...
    }
}
