//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Willowcat.EbookCreatorTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Willowcat.EbookCreatorTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;
        ///&lt;package xmlns=&quot;http://www.idpf.org/2007/opf&quot; version=&quot;3.0&quot; xml:lang=&quot;en-US&quot; unique-identifier=&quot;uid&quot;&gt;
        ///  &lt;metadata xmlns:calibre=&quot;http://calibre.kovidgoyal.net/2009/metadata&quot; xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///    &lt;dc:identifier id=&quot;uid&quot; p7:scheme=&quot;uuid&quot; xmlns:p7=&quot;http://www.idpf.org/2007/opf&quot;&gt;1ed2e6a5-acde-4492-9bee-62d0df446cc1&lt;/dc:identifier&gt;
        ///    &lt;dc:title&gt;the [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string contents_basic {
            get {
                return ResourceManager.GetString("contents_basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;
        ///&lt;package xmlns=&quot;http://www.idpf.org/2007/opf&quot; version=&quot;3.0&quot; xml:lang=&quot;en-US&quot; unique-identifier=&quot;uid&quot;&gt;
        ///  &lt;metadata xmlns:calibre=&quot;http://calibre.kovidgoyal.net/2009/metadata&quot; xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///    &lt;dc:identifier id=&quot;uid&quot; p7:scheme=&quot;uuid&quot; xmlns:p7=&quot;http://www.idpf.org/2007/opf&quot;&gt;1ed2e6a5-acde-4492-9bee-62d0df446cc1&lt;/dc:identifier&gt;
        ///    &lt;dc:title&gt;the [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string contents_customfields {
            get {
                return ResourceManager.GetString("contents_customfields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;
        ///&lt;package xmlns=&quot;http://www.idpf.org/2007/opf&quot; version=&quot;3.0&quot; xml:lang=&quot;en-US&quot; unique-identifier=&quot;uid&quot;&gt;
        ///  &lt;metadata xmlns:calibre=&quot;http://calibre.kovidgoyal.net/2009/metadata&quot; xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///    &lt;dc:identifier id=&quot;uid&quot; p7:scheme=&quot;uuid&quot; xmlns:p7=&quot;http://www.idpf.org/2007/opf&quot;&gt;1ed2e6a5-acde-4492-9bee-62d0df446cc1&lt;/dc:identifier&gt;
        ///    &lt;dc:title&gt;the [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string contents_customfields_2 {
            get {
                return ResourceManager.GetString("contents_customfields_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;
        ///&lt;package xmlns=&quot;http://www.idpf.org/2007/opf&quot; version=&quot;3.0&quot; xml:lang=&quot;en-US&quot; unique-identifier=&quot;uid&quot;&gt;
        ///  &lt;metadata xmlns:calibre=&quot;http://calibre.kovidgoyal.net/2009/metadata&quot; xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///    &lt;dc:identifier id=&quot;uid&quot; p7:scheme=&quot;uuid&quot; xmlns:p7=&quot;http://www.idpf.org/2007/opf&quot;&gt;1ed2e6a5-acde-4492-9bee-62d0df446cc1&lt;/dc:identifier&gt;
        ///    &lt;dc:title&gt;the [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string contents_customfields_notime {
            get {
                return ResourceManager.GetString("contents_customfields_notime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;
        ///&lt;package xmlns=&quot;http://www.idpf.org/2007/opf&quot; version=&quot;3.0&quot; xml:lang=&quot;en-US&quot; unique-identifier=&quot;uid&quot;&gt;
        ///  &lt;metadata xmlns:calibre=&quot;http://calibre.kovidgoyal.net/2009/metadata&quot; xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///    &lt;dc:identifier id=&quot;uid&quot; p7:scheme=&quot;uuid&quot; xmlns:p7=&quot;http://www.idpf.org/2007/opf&quot;&gt;1ed2e6a5-acde-4492-9bee-62d0df446cc1&lt;/dc:identifier&gt;
        ///    &lt;dc:title&gt;the [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string contents_language {
            get {
                return ResourceManager.GetString("contents_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;
        ///&lt;package xmlns=&quot;http://www.idpf.org/2007/opf&quot; version=&quot;3.0&quot; xml:lang=&quot;en-US&quot; unique-identifier=&quot;uid&quot;&gt;
        ///  &lt;metadata xmlns:calibre=&quot;http://calibre.kovidgoyal.net/2009/metadata&quot; xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///    &lt;dc:identifier id=&quot;uid&quot; p7:scheme=&quot;uuid&quot; xmlns:p7=&quot;http://www.idpf.org/2007/opf&quot;&gt;1ed2e6a5-acde-4492-9bee-62d0df446cc1&lt;/dc:identifier&gt;
        ///    &lt;dc:title&gt;the [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string contents_oldformat {
            get {
                return ResourceManager.GetString("contents_oldformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;
        ///&lt;package xmlns=&quot;http://www.idpf.org/2007/opf&quot; version=&quot;3.0&quot; xml:lang=&quot;en-US&quot; unique-identifier=&quot;uid&quot;&gt;
        ///  &lt;metadata xmlns:calibre=&quot;http://calibre.kovidgoyal.net/2009/metadata&quot; xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///    &lt;dc:identifier id=&quot;uid&quot; p7:scheme=&quot;uuid&quot; xmlns:p7=&quot;http://www.idpf.org/2007/opf&quot;&gt;1ed2e6a5-acde-4492-9bee-62d0df446cc1&lt;/dc:identifier&gt;
        ///    &lt;dc:title&gt;the [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string contents_proofreader {
            get {
                return ResourceManager.GetString("contents_proofreader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;
        ///&lt;package xmlns=&quot;http://www.idpf.org/2007/opf&quot; version=&quot;3.0&quot; xml:lang=&quot;en-US&quot; unique-identifier=&quot;uid&quot;&gt;
        ///  &lt;metadata xmlns:calibre=&quot;http://calibre.kovidgoyal.net/2009/metadata&quot; xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///    &lt;dc:identifier id=&quot;uid&quot; p7:scheme=&quot;uuid&quot; xmlns:p7=&quot;http://www.idpf.org/2007/opf&quot;&gt;1ed2e6a5-acde-4492-9bee-62d0df446cc1&lt;/dc:identifier&gt;
        ///    &lt;dc:title&gt;the [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string contents_series {
            get {
                return ResourceManager.GetString("contents_series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;
        ///&lt;package xmlns=&quot;http://www.idpf.org/2007/opf&quot; version=&quot;3.0&quot; xml:lang=&quot;en-US&quot; unique-identifier=&quot;uid&quot;&gt;
        ///  &lt;metadata xmlns:calibre=&quot;http://calibre.kovidgoyal.net/2009/metadata&quot; xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///    &lt;dc:identifier id=&quot;uid&quot; p7:scheme=&quot;uuid&quot; xmlns:p7=&quot;http://www.idpf.org/2007/opf&quot;&gt;1ed2e6a5-acde-4492-9bee-62d0df446cc1&lt;/dc:identifier&gt;
        ///    &lt;dc:title&gt;the [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string contents_tags {
            get {
                return ResourceManager.GetString("contents_tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;
        ///&lt;package xmlns=&quot;http://www.idpf.org/2007/opf&quot; version=&quot;3.0&quot; xml:lang=&quot;en-US&quot; unique-identifier=&quot;uid&quot;&gt;
        ///  &lt;metadata xmlns:calibre=&quot;http://calibre.kovidgoyal.net/2009/metadata&quot; xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///    &lt;dc:identifier id=&quot;uid&quot; p7:scheme=&quot;uuid&quot; xmlns:p7=&quot;http://www.idpf.org/2007/opf&quot;&gt;1ed2e6a5-acde-4492-9bee-62d0df446cc1&lt;/dc:identifier&gt;
        ///    &lt;dc:title&gt;the [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string contents_timeread {
            get {
                return ResourceManager.GetString("contents_timeread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;  encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;package xmlns=&quot;http://www.idpf.org/2007/opf&quot; unique-identifier=&quot;uuid_id&quot; version=&quot;2.0&quot;&gt;
        ///  &lt;metadata xmlns:calibre=&quot;http://calibre.kovidgoyal.net/2009/metadata&quot; xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot; xmlns:opf=&quot;http://www.idpf.org/2007/opf&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///    &lt;dc:title&gt;Title&lt;/dc:title&gt;
        ///    &lt;dc:creator opf:role=&quot;aut&quot; opf:file-as=&quot;leletha&quot;&gt;Creator Name&lt;/dc:creator&gt;
        ///    &lt;dc:publis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string contents_version2 {
            get {
                return ResourceManager.GetString("contents_version2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;
        ///&lt;package xmlns=&quot;http://www.idpf.org/2007/opf&quot; unique-identifier=&quot;uuid_id&quot; version=&quot;2.0&quot;&gt;
        ///  &lt;metadata xmlns:calibre=&quot;http://calibre.kovidgoyal.net/2009/metadata&quot; xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot; xmlns:opf=&quot;http://www.idpf.org/2007/opf&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///    &lt;dc:title&gt;Title&lt;/dc:title&gt;
        ///    &lt;dc:creator opf:role=&quot;aut&quot; opf:file-as=&quot;leletha&quot;&gt;Creator Name&lt;/dc:creator&gt;
        ///    &lt;dc:publish [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string contents_version2_withtime {
            get {
                return ResourceManager.GetString("contents_version2_withtime", resourceCulture);
            }
        }
    }
}
